package com.dereekb.gae.server.auth.deprecated.permissions.visit;

import com.dereekb.gae.server.auth.deprecated.permissions.PermissionsReader;
import com.dereekb.gae.server.auth.deprecated.permissions.evaluator.PermissionsEvent;
import com.dereekb.gae.server.auth.deprecated.permissions.evaluator.PermissionsHandler;

/**
 * Base permissions class.
 * @author dereekb
 *
 */
@Deprecated
public abstract class VisitPermissionsHandler implements PermissionsHandler {

	private static final String permissionsPrefix = "visit";

	@Override
	public String getPermissionStringPrefix() {
		return permissionsPrefix;
	}

	@Override
	public boolean hasPermission(PermissionsEvent event) {
		return this.hasPermissionStringCheck(event);
	}

	/**
	 * Checks to see if the current Authentication has the permission generated by the request.
	 *
	 * @param event
	 * @return True if the user has permission.
	 */
	protected boolean hasPermissionStringCheck(PermissionsEvent event) {
		String permissionString = this.getPermissionStringForRequest(event.getRequest());
		boolean hasPermission = PermissionsReader.hasPermission(permissionString, event);
		return hasPermission;
	}

	public String getPermissionStringForRequest(String request) {
		String prefix = this.getPermissionStringPrefix();
		String permissionString = prefix + "." + request;
		return permissionString;
	}

}
