pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
        }
    }
    environment {
        ARTIFACTORY_CREDS = credentials('jenkins-artifactory')
        ARTIFACTORY_CONTEXT_URL = "https://dev.dereekb.com:10000/artifactory"
    }
    stages {
        stage('Initialize') {
            steps {
                sh './jenkins/scripts/initialize.sh'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh './jenkins/scripts/deploy.sh'
            }
        }
    }
}