pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy To Artifactory') {
            environment {
                ARTIFACTORY_CREDS = credentials('jenkins-artifactory')
                ARTIFACTORY_CONTEXT_URL = "https://dev.dereekb.com:10000/artifactory"
            }
            steps {
                sh './jenkins/scripts/artifactory-deploy.sh'
            }
        }
    }
}