pipeline {
    agent {
        dockerfile {
            label 'maven'
            filename 'Dockerfile'
            dir 'jenkins/maven'
            args '-v $HOME/.m2:/root/.m2'
        }
        dockerfile {
            label 'node'
            filename 'Dockerfile'
            dir 'jenkins/node'
        }
    }
    environment {
        ARTIFACTORY_CREDS = credentials('jenkins-artifactory')
        ARTIFACTORY_CONTEXT_URL = "https://dev.dereekb.com:10000/artifactory"
        NPM_TOKEN = credentials('jenkins-verdaccio')
    }
    stages {
        stage('Initialize') {
            failFast true
            parallel {
                stage('Appengine') {
                    agent { label 'maven' }
                    steps {
                        sh './jenkins/scripts/appengine/initialize.sh'
                    }
                }
                stage('Angular') {
                    agent { label 'node' }
                    steps {
                        sh './jenkins/scripts/appengine-web/initialize.sh'
                    }
                }
            }
        }
        stage('Testing') {
            failFast false
            parallel {
                stage('Appengine') {
                    agent { label 'maven' }
                    stages {
                        stage('Build Appengine') {
                            steps {
                                sh './jenkins/scripts/appengine/build.sh'
                            }
                        }
                        stage('Test Appengine') {
                            steps {
                                sh './jenkins/scripts/appengine/test.sh'
                            }
                            post {
                                always {
                                    junit 'appengine/target/surefire-reports/*.xml'
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('E2E') {
            steps {
                sh 'echo Testing E2E...'
            }
        }
        stage('Deploy') {
            failFast true
            parallel {
                stage('Appengine') {
                    agent { label 'maven' }
                    steps {
                        sh './jenkins/scripts/appengine/deploy.sh'
                    }
                }
            }
        }
    }
}