version: '3'
services:
  gae-default-service:
    build:
      context: ./
      dockerfile: ./docker/services/Dockerfile
      args:
        SERVER_CONTEXT_DIR: ./gae-default-service
    ports:
     - "8080"
     - "8888"
  gae-event-service:
    build:
      context: ./
      dockerfile: ./docker/services/Dockerfile
      args:
        SERVER_CONTEXT_DIR: ./gae-event-service
    ports:
     - "8080"
     - "8888"
  gae-login-service:
    build:
      context: ./
      dockerfile: ./docker/services/Dockerfile
      args:
        SERVER_CONTEXT_DIR: ./gae-login-service
    ports:
     - "8080"
     - "8888"
